### ISSUE TITLE
How to set expiry time of message sent to device? 

### ISSUE THREAD

**Issue by arathod-eic** [Azure/azure-iot-service-sdk-java#10]
I am trying to upgrade to the 2.X.X releases from the 1.34.2 SDK version.

In the previous release, a method was available to set the expiry of a message sent to the device.

As per my understanding, the package has been changed to com.microsoft.azure.sdk.iot.service.messaging.Message in 2.1.5 from com.microsoft.azure.sdk.iot.service.Message in 1.34.2 for the Message class.

Method name in v1.34.2 in Message Class : setExpiryTimeUtc(long milliseconds)

Is there any new method of setting an expiry to the message?

Appreciate the help. Thanks.

**Comment by 5putejayesh** [comment]
How to set expired time of c2D message in azure iot service sdk so that it can overirde the default expired time which is set in iot hub.
I am using below version of azure-iot-service-sdk java
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-service-client</artifactId>
	<version>2.1.5</version>
</dependency>

In earlier version setExpirytime method was available which is missing in latest version.
I have tried to set expiry time in message properties as below but it is not working.

Code snippet tried to set expired time from message properties:-

Message messageToSend = new Message("Some message text");
messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);
long expiryTimeMillis = System.currentTimeMillis() + (2*60000); 

	properties.put("expiryTimeUtc", Long.toString(expiryTimeMillis));
			properties.put("defaultTtlAsIso8601", Long.toString(expiryTimeMillis));
			properties.put("absolute-expiry-time", Long.toString(expiryTimeMillis));
			messageToSend.setProperties(properties);
default ttl in azure portla is 1hour,after setting above properties message is not expired after 2 mins.
Please provide some workaround for this.

**Comment by 5putejayesh** [comment]
Hi @arathod-eic are you able to set TTL in 2.X.X

**Comment by arathod-eic** [comment]
@5putejayesh , no. Also, I am not able to find any reference to set the expiry time in any azure documents. If you find any solution please share it with me also.

**Comment by ethanann-ms** [comment]
expiryTimeUtc variable with Get/Set methods have been added back to Message class in 2.1.8
